name: CI

on:
  push:
    branches: [ develop, main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Implementation Guide
        run: |
          docker run \
            -v $(pwd):/home/publisher/ig \
            hl7fhir/ig-publisher-base \
            sh -c "sushi && \
            echo '#!/bin/bash' > _updatePublisher.sh && \
            echo 'curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o input-cache/publisher.jar --create-dirs' >> _updatePublisher.sh && \
            echo '#!/bin/bash' > _genonce.sh && \
            echo 'java -jar input-cache/publisher.jar -ig .' >> _genonce.sh && \
            chmod +x _updatePublisher.sh _genonce.sh && \
            ./_updatePublisher.sh && ./_genonce.sh"